PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
alias ga='git add'
alias gaa='git add --all'
alias gamend='git commit --amend'
alias gbr='git branch -v'
alias gba='git branch -a'
alias gbl='git blame'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcot='git checkout -t'
alias gchanges='git diff --name-status -r'
alias gd='git diff'
alias gdc='git diff --cached'
alias gdiffstat='git diff --stat -r'
alias gl='!git_pretty_log'
alias glog='git log'
alias glogb='git log --graph --abbrev-commit --date=relative --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset"'
alias glogp='git log --pretty=format:"%h %s" --graph'
alias gm='git merge'
alias gp='git pull --rebase'
alias gpu='git push -u origin'
alias gr='git rebase -i'
alias gs='git status -s'
alias gw='git whatchanged'
